# Generated by Django 3.1.3 on 2020-12-04 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201204_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 21, 44, 24, 712180, tzinfo=utc)),
        ),
    ]
