# Generated by Django 3.1.3 on 2020-12-11 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201208_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 17, 33, 10, 99029, tzinfo=utc)),
        ),
    ]
