# Generated by Django 3.1.3 on 2020-12-13 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201211_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 16, 47, 55, 301957, tzinfo=utc)),
        ),
    ]
