# Generated by Django 3.1.3 on 2020-12-24 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201221_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 19, 21, 49, 807228, tzinfo=utc)),
        ),
    ]
