# Generated by Django 3.1.3 on 2020-12-24 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201224_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 19, 38, 2, 453152, tzinfo=utc)),
        ),
    ]
