# Generated by Django 3.1.3 on 2020-12-29 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201228_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 18, 2, 16, 657645, tzinfo=utc)),
        ),
    ]
