# Generated by Django 3.1.3 on 2020-12-29 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201229_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 18, 42, 21, 736866, tzinfo=utc)),
        ),
    ]
