# Generated by Django 3.1.3 on 2021-01-04 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210104_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 19, 30, 17, 317183, tzinfo=utc)),
        ),
    ]
