# Generated by Django 3.1.3 on 2021-01-04 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210104_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 20, 13, 38, 276058, tzinfo=utc)),
        ),
    ]
