# Generated by Django 3.1.3 on 2021-01-08 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210104_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 20, 53, 17, 206854, tzinfo=utc)),
        ),
    ]
