# Generated by Django 3.1.3 on 2021-01-09 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210108_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 15, 8, 54, 849512, tzinfo=utc)),
        ),
    ]
