# Generated by Django 3.1.3 on 2021-01-17 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210109_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 19, 56, 52, 908266, tzinfo=utc)),
        ),
    ]
