# Generated by Django 3.1.3 on 2021-01-19 02:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210117_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 2, 25, 50, 696749, tzinfo=utc)),
        ),
    ]
