# Generated by Django 3.1.3 on 2021-01-20 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210119_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 10, 27, 961146, tzinfo=utc)),
        ),
    ]
