# Generated by Django 3.1.3 on 2020-12-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='info/')),
                ('description', models.TextField(max_length=200)),
                ('fb_link', models.EmailField(max_length=200)),
                ('twitter_link', models.EmailField(max_length=200)),
                ('instgram_link', models.EmailField(max_length=200)),
                ('address', models.TextField(max_length=2000)),
                ('phone_number', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=100)),
            ],
        ),
    ]
