# Generated by Django 3.1.3 on 2020-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='fb_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='instgram_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='twitter_link',
            field=models.URLField(),
        ),
    ]
