# Generated by Django 3.1.3 on 2020-12-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20201224_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreview',
            name='cleaning_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomreview',
            name='eat_rate',
            field=models.IntegerField(default=0),
        ),
    ]
