# Generated by Django 3.1.3 on 2020-12-27 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20201225_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreview',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
