# Generated by Django 3.1.3 on 2021-01-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210104_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_location', to='property.places'),
        ),
    ]
