# Generated by Django 3.1.3 on 2021-01-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210104_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='loction_in_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
