# Generated by Django 3.1.3 on 2021-01-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_room_loction_in_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
