# Generated by Django 3.1.3 on 2021-01-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icon_image'),
        ),
    ]
